fwfe

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -10,11 +10,6 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
-      - name: Check Formatting
-        run: |
-          dotnet tool install --global dotnet-format
-          dotnet format --check
-
       - name: Setup .NET
         uses: actions/setup-dotnet@v2
         with:
@@ -39,3 +34,13 @@ jobs:
         run: |
           cd SpaceBattle/SpaceBattle.Lib.Tests/
           dotnet coverlet bin/Debug/net8.0/SpaceBattle.Lib.Tests.dll --target "dotnet" --targetargs "test --no-build" -f=opencover -o="coverage.xml"
+
+      - name: Check Formatting
+        run: |
+          dotnet tool install --global dotnet-format
+          dotnet format --check
+
+          # Проверка наличия пустой строки в конце каждого файла
+          find . -type f -print0 | while IFS= read -r -d $'\0' file; do
+            tail -n 1 "$file" | grep -q '^$' || { echo "Error: File '$file' does not end with an empty line."; exit 1; }
+          done
